name: Build & Release

on:
  workflow_call:
  workflow_dispatch:
#  push:
#    branches:
#      - '**'
#    tags:
#      - 'v[0-9]+.[0-9]+.[0-9]+'
#    paths:
#      - '.github/workflows/build-and-release.yml'
#      - '.github/scripts/**'
#      - 'client/**'
#      - 'sdk/python/packages/**'
#      - 'packages/flet/**'
#      - '.fvmrc'

permissions:
  id-token: write
  contents: write

concurrency:
  group: build-and-release-${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref_name }}
  cancel-in-progress: true

env:
  ROOT: "${{ github.workspace }}"
  SDK_PYTHON: "${{ github.workspace }}/sdk/python"
  SCRIPTS: "${{ github.workspace }}/.github/scripts"
  UV_PYTHON: "3.12.7"

jobs:
  # ============
  # Python tests
  # ============
  python_tests:
    name: Python ${{ matrix.python-version }} tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}