name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_and_release:
    name: Build & Release
    uses: ./.github/workflows/build-and-release.yml
    permissions:
      id-token: write
      contents: write

  macos_integration_tests:
    name: macOS Integration Tests
    uses: ./.github/workflows/macos-integration-tests.yml
    permissions:
      contents: read
